# Generated by Django 3.1.4 on 2021-03-11 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='album',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
