# Generated by Django 3.1.4 on 2021-03-11 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0003_album_track'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductPriceMinQtyPromotion',
        ),
    ]
