# Generated by Django 3.1.4 on 2021-03-11 07:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0004_delete_productpriceminqtypromotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPriceMinQtyPromotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('min_order_qty', models.IntegerField(default=0)),
                ('create_date', models.DateField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TheApp.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
