# Generated by Django 3.1.4 on 2021-03-15 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0006_auto_20210315_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=5),
        ),
        migrations.AlterField(
            model_name='productpriceminqtypromotion',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=5),
        ),
    ]
