# Generated by Django 3.1.4 on 2021-03-18 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TheApp', '0007_auto_20210315_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_qty', models.IntegerField(default=0)),
                ('order_product_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('cartheader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TheApp.cartheader')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TheApp.product')),
            ],
        ),
    ]
