# Generated by Django 3.1.4 on 2026-06-16 07:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TheApp', '0008_cartheader_cartline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('detail', models.TextField(max_length=5000)),
                ('slug', models.SlugField(default='', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='menuitems',
            name='topbar_option',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='app',
            field=models.CharField(default='TheApp', max_length=128),
        ),
    ]
